### ISSUE TITLE
cannot close new window - introduced in FF38

### ISSUE THREAD

**Issue by zuber1979** [Infocatcher/Private_Tab#175] opened 2015-05-15 12:57 UTC
When new crippled window (without tabs, bookmarks, etc.) is opened (like when clicked on Gmail new email notification) i cannot be closed anymore. And then also Firefox cannot be closed anymore.

**Comment by Infocatcher** [comment] 2015-05-18 19:17
Strange, looks like I can't reproduce...
Please try, how works here:
http://infocatcher.ucoz.net/ext/fx/right_links/testcase.html
for `javascript: window.open(location.href, '', 'width=300,height=300'); void(0);` link.

**Comment by zuber1979** [comment] 2015-05-18 20:53
I can reproduce this on my side with the link You mentioned.

I'm using Cyberfox 38.0.1 x64 right now.

And I think important thing is to restart the browser after installing the add-on.

Maybe it is also influence of some other add-ons? But I don't have many of them. And when the problem ocured I tried disabling one by one and then I found that Privatetab is causing the problem.

regards

**Comment by Infocatcher** [comment] 2015-05-20 11:44
Strange. Is there something related in Browser Console (Ctrl+Shift+J)?
Also please enable debug messages in about:config:
extensions.privateTab.debug = true
May be something will help me to understand, that goes wrong.

**Comment by dyphacie** [comment] 2015-05-20 13:36
When closing a window the Browser Console shows :
> Tabmix.RecentWindow is undefined tablib.js:1777:0
> [Private Tab] 13:41:780 windowClosingHandler() [close]
> [Private Tab] 13:41:780 close: Someone already prevent window closing

Now as you can see I think is an issue with the tabmixplus addon and updating to the last development version fixed it for me.

What is strange is that when I tested it with a clean profile this issue didn't happen.

**Comment by zuber1979** [comment] 2015-05-20 17:15
I can confirm, after installing TabMixPlus 0.4.1.8pre.150317a1 problem disappeared.

**Comment by icaroperseo** [comment] 2015-05-27 00:32
I also have the same problem, apparently came up with this new version of Firefox (38) because in previous versions that did not happen. In my case, I noticed the problem when using [Wallabag addon](https://addons.mozilla.org/es/firefox/addon/wallabag/) which opens a popup window to fulfill its function. You can work with it normally but it is impossible to close this popup window. The only way is finalizing the process. The same problem came up with [InstantFox](http://www.instantfox.net/) (same procedure as above).

Try to resolve it through the creation of a new profile in Firefox, disabling graphics acceleration, among other options but nothing worked. I discovered that the problem was due to a Firefox addon (I created a new profile and added to Wallabag to the same and everything worked out great), after searching for a long time I discovered it was your addon. I had no opportunity to try different popups.

(I forgot to mention that before the appearance of this problem I was using Private Tab and Wallabag without problems. [?])

I hope this is useful, if not, just let me know what you need and I'll try to help.

Best regards.

**Comment by Infocatcher** [comment] 2015-08-20 22:15
This was a conflict with Tab Mix Plus and therefore can be closed.

**Closed by Infocatcher** 2015-08-20 22:15 UTC
Labels: conflict with another addon
