### ISSUE TITLE
rememberClosedPrivateTabs doesn't work in FF>29.0

### ISSUE THREAD

**Issue by sdavidg** [Infocatcher/Private_Tab#146] opened 2014-05-18 19:26 UTC
"extensions.privateTab.rememberClosedPrivateTabs" preference doesn't work in FF>29.0

**Comment by Infocatcher** [comment] 2015-05-10 16:31
Oh, looks fixed for me and now (finally!) will be released soon.

**Closed by Infocatcher** 2015-05-10 16:31 UTC
Labels: bug, compatibility

**Comment by sdavidg** [comment] 2015-05-11 06:56
I have update to latest version and the behavior is a bit different.
1) Open two private tabs
2) Close one of them
3) Reopen the tab (ctrl+shift+t)
4) Reopened tab is not private, this is a bug?

**Comment by Infocatcher** [comment] 2015-05-14 11:46
>  4) Reopened tab is not private, this is a bug?

Interesting... I can't reproduce, but which tab is active during reopening (private or not)?

**Comment by sdavidg** [comment] 2015-05-14 19:53
No matter which tab is active. 
The error only occurs on W -XP (yes, it is a very old) . Windows7 working properly.

**Comment by sdavidg** [comment] 2015-05-22 06:31
> No matter which tab is active

I was wrong. If selected tab is private, tab reopened is public. If the selected tab is public, reopened tab is private. Tested in Windows-XP

**Comment by sdavidg** [comment] 2015-07-30 06:20
1) Open one private tab
2) Open some links via "ctrl+click"
3) Right click on tab and select "Close Tabs to the Right"
4) Reopen tabs via "ctrl+shift+T"
5) Some reopened tabs are public. This bug occurs only sometimes

The test case on comment https://github.com/Infocatcher/Private_Tab/issues/146#issuecomment-100789488 also works sometimes

Windows 7, W-XP
FF 39.0
Private Tab 0.1.7.5.1

**Comment by Infocatcher** [comment] 2015-08-20 22:10
Oh, I still unable to reproduce, but may be something useful in debug logs:
_extensions.privateTab.debug_ = true in about:config
and then see for `[Private Tab] …` messages in error/browser console (Ctrl+Shift+J)

**Comment by sdavidg** [comment] 2015-08-21 11:39
--Open private tab from another private tab via ctrl+click
[Private Tab] 32:08:887 Tab opened: (not empty) Inherit private state: true
[Private Tab] 32:08:887 Set usePrivateBrowsing to true Tab: 
[Private Tab] 32:09:612 [patcher] gBrowser.setIcon(): isPrivate = true
[Private Tab] 32:09:612 PrivateBrowsingUtils.isWindowPrivate(): override to true
[Private Tab] 32:09:613 PrivateBrowsingUtils.isWindowPrivate(): override to true
[Private Tab] 32:10:810 updateTabTooltip()

--Close tab (middle click)
[Private Tab] 32:44:015 tabClosingHandler(): save closed private tab in undo close history

--Reopened tab (tab is public)
[Private Tab] 32:47:137 Tab opened: Nueva pestaña (empty) Inherit private state: undefined
[Private Tab] 32:47:157 setWindowBusy(): true
[Private Tab] 32:47:158 setWindowBusy(): false
[Private Tab] 32:47:186 updateWindowTitle() Mozilla Firefox
[Private Tab] 32:47:270 updateTabsInTitlebar() => TabsInTitlebar._update(true)
[Private Tab] 32:47:287 Tab restored: rememberClosedPrivateTabs broken in FF38 · Issue #173 · Infocatcher/Private_Tab · GitHub
[Private Tab] 32:47:336 updateDownloadPanel() => reinitialize download indicator
[Private Tab] 32:47:770 updateTabTooltip()

**Comment by Infocatcher** [comment] 2015-08-21 13:13
Interesting...
Test version with a bit more useful debug logs (I hope):
<a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.1.8.1pre-fx-sm.xpi">private_tab-0.1.8.1pre-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/cc5e06ed67f912bd0f6a78854dc1ace991b31bcb">source</a>)
(changed only `Tab restored:` message)

**Comment by sdavidg** [comment] 2015-08-21 14:25
--Open private tab from another private tab via ctrl+click
[Private Tab] 20:39:365 Tab opened: (not empty) Inherit private state: true
[Private Tab] 20:39:365 Set usePrivateBrowsing to true Tab: 
[Private Tab] 20:40:165 updateTabTooltip()
[Private Tab] 20:40:779 [patcher] gBrowser.setIcon(): isPrivate = true
[Private Tab] 20:40:779 PrivateBrowsingUtils.isWindowPrivate(): override to true

--Close tab (middle click)
[Private Tab] 21:04:483 tabClosingHandler(): save closed private tab in undo close history

--Reopened tab (tab is public)
[Private Tab] 21:08:967 Tab opened: Nueva pestaña (empty) Inherit private state: undefined
[Private Tab] 21:08:983 setWindowBusy(): true
[Private Tab] 21:08:984 setWindowBusy(): false
[Private Tab] 21:09:015 updateWindowTitle() Mozilla Firefox
[Private Tab] 21:09:094 updateTabsInTitlebar() => TabsInTitlebar._update(true)
[Private Tab] 21:09:112 Tab restored, has private attribute: false, label: Private Tab :: Complementos para Firefox
[Private Tab] 21:09:157 updateDownloadPanel() => reinitialize download indicator
[Private Tab] 21:09:594 updateTabTooltip()

**Comment by Infocatcher** [comment] 2015-08-21 14:41
> Tab restored, has private attribute: false

This is strange... This means that private attribute wasn't saved in session.
If there is this attribute, tab should be underlined (so, this is visible, if something went wrong at that stage).

**Comment by sdavidg** [comment] 2015-08-21 17:28
Sometimes it works. When it works, the log that is displayed when the tab is closed:

--Close tab (middle click)
[Private Tab] 24:44:842 updateTabTooltip()
**[Private Tab] 24:44:980 dontSaveClosedPrivateTabs(true): create wrapper for PrivacyFilter**
**[Private Tab] 24:44:980 tabClosingHandler(): save closed private tab in undo close history**

If the last two lines do not appear on the log, the tab will be reopened public.

David

**Comment by Infocatcher** [comment] 2015-08-22 22:21
> If the last two lines do not appear on the log, the tab will be reopened public.

Very weird things... This means that built-in session store mechanism doesn't treat tab as private.
May be due to queue delays from chrome://browser/content/content-sessionStore.js
```js
  /**
   * The delay (in ms) used to delay sending changes after data has been
   * invalidated.
   */
  BATCH_DELAY_MS: 1000,
```

Updated test version with yet another debug message (da243f9cf89f2b6d2fa56718428bb95fe2cbacd5):
<a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.1.8.1pre-fx-sm.xpi">private_tab-0.1.8.1pre-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/da243f9cf89f2b6d2fa56718428bb95fe2cbacd5">source</a>)

**Comment by sdavidg** [comment] 2015-08-23 16:52
[Private Tab] 49:01:840 Tab opened: (not empty)
Inherit private state: true
[Private Tab] 49:01:840 Set usePrivateBrowsing to true
Tab: 
[Private Tab] 49:02:250 [patcher] gBrowser.setIcon(): isPrivate = true
[Private Tab] 49:02:250 PrivateBrowsingUtils.isWindowPrivate(): override to true2
[Private Tab] 49:05:440 tabClosingHandler(): save closed private tab in undo close history
[Private Tab] 49:07:631 Tab opened: Nueva pestaña (empty)
Inherit private state: undefined
[Private Tab] 49:07:644 setWindowBusy(): true
[Private Tab] 49:07:644 setWindowBusy(): false
[Private Tab] 49:07:683 updateWindowTitle() Mozilla Firefox
[Private Tab] 49:07:747 updateTabsInTitlebar() => TabsInTitlebar._update(true)
[Private Tab] 49:07:763 Tab restored, has private attribute: false, label: Infocatcher/Private_Tab at cc5e06ed67f912bd0f6a78854dc1ace991b31bcb · GitHub
[Private Tab] 49:07:810 updateDownloadPanel() => reinitialize download indicator
[Private Tab] 49:10:154 updateTabTooltip()

It may be a conflict with another extension?

**Comment by Infocatcher** [comment] 2015-08-25 12:35
> It may be a conflict with another extension?

May be. Or may be this is due to session store optimizations: private attribute was actually added, but not yet saved into session data.

**Comment by Infocatcher** [comment] 2015-08-26 10:16
> tabClosingHandler(): save closed private tab in undo close history
> ...
> Tab restored, has private attribute: false

Strange... May be this will help: 26663d7f8d4a9869ce6a2104e4082efcca67c2c1
Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.1.8.1pre2-fx-sm.xpi">private_tab-0.1.8.1pre2-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/26663d7f8d4a9869ce6a2104e4082efcca67c2c1">source</a>).

**Comment by sdavidg** [comment] 2015-09-02 16:31
1) Open Firefox with the attached Profile(https://dl.dropboxusercontent.com/u/245317/profile_example_private_tab.7z)
2) Right-click on bookmark "Example" and open on new Private tab
3) Open the link "source"  via "ctrl+click"
4) Close tab
5) Reopen tab via "ctrl+shift+T" --> Reopened tab is not private

Note: If you turn off the style "SVG CuteMenus" tab correctly reopens (???)
I'm looking for a simple test case in W7


Windows W-XP
FF 40.0.3
Private Tab  0.1.8.1pre2

**Comment by Infocatcher** [comment] 2015-09-04 16:03
Something break `browser.webProgress.isLoadingDocument` for just restored tab, I'm not sure, what actually happens, but now looks fixed for me.
Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.1.8.1pre3-fx-sm.xpi">private_tab-0.1.8.1pre3-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/2ec90725845b6d07067c846bd2276f6b3a2956df">source</a>).

**Comment by sdavidg** [comment] 2015-09-04 18:41
It works perfectly. I will test more next week when I get back to work.
Thank you very much

**Comment by sdavidg** [comment] 2015-09-14 14:11
I tested it for a week, and works well.
Thanks again

**Comment by Infocatcher** [comment] 2015-09-14 16:05
> I tested it for a week, and works well.

Great!
