### ISSUE TITLE
Compatibility with Firefox 51+

### ISSUE THREAD

**Issue by dehghani-mehdi** [Infocatcher/Private_Tab#237] opened 2016-11-17 09:18 UTC
Hi,

Please add  support for Firefox v52.x

Thank you !

**Comment by Infocatcher** [comment] 2016-11-17 17:24
See
https://bugzilla.mozilla.org/show_bug.cgi?id=1315233#c24
https://bugzilla.mozilla.org/show_bug.cgi?id=1315233#c27
https://bugzilla.mozilla.org/show_bug.cgi?id=1318388

This is forced compatibility from AMO side...
I need feedback from Firefox developers to do something with this.

Also extensions.checkCompatibility.<ins>52</ins>.0 = false (for Firefox <ins>52</ins>) in about:config should allow to install/use anyway.

**Comment by Dimas-sc** [comment] 2016-11-17 18:36
Hope they will answer soon, now we don't have Private Tab on Firefox 51 beta :( I voted for the bug

**Comment by Infocatcher** [comment] 2016-11-17 18:41
Oh,

(https://bugzilla.mozilla.org/show_bug.cgi?id=1315233#c33)
>> Also... The most important question.
>> How correctly implement private tabs?

> See above, but I'm not sure there's really any "correct" way without a lot of
> platform changes, at this point. But we can continue this conversation in the
> other bug.

О_О

**Comment by Dimas-sc** [comment] 2016-12-20 20:00
Do you have a plan now that bug is "fixed"? :(

**Comment by Infocatcher** [comment] 2016-12-26 07:54
> Do you have a plan now that bug is "fixed"? :(

See https://bugzilla.mozilla.org/show_bug.cgi?id=1318388#c35

So, I don't see any way to fix this from my side. :(

May me is needed more feedback from users: more bugs on https://bugzilla.mozilla.org/ and more comments...

**Comment by Infocatcher** [comment] 2017-01-14 18:32
Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.2.1pre-fx-sm.xpi">private_tab-0.2.1pre-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/898856115424aca6499eb272c1a82c31e808a318">source code</a>).

Now will be opened duplicated tab to toggle private state of already opened tab, so _extensions.privateTab.toggleTabPrivateAutoReload_ and _extensions.privateTab.toggleTabPrivateAutoReload.stopLoading_ haven't effect.
Also all private data may be cleared like after closing of all private tabs and windows: https://bugzilla.mozilla.org/show_bug.cgi?id=1329912 (so, should be opened at least one remote private tab to leave data).

**Comment by harl** [comment] 2017-01-14 20:04
Looks good so far. The icon is back (I had to re-add it to the bar) and it simply opens a "New Tab" tab in private browsing mode, ready to be used even with TMP's feature to always open a new tab from the address bar (because it re-uses the current tab if it's a "New Tab"). Will check back if I find anything unusual.

**Comment by Infocatcher** [comment] 2017-01-18 19:54
https://github.com/Infocatcher/Private_Tab/releases/tag/0.2.1
I hope, will appear soon: https://addons.mozilla.org/addon/private-tab/versions/0.2.1

**Closed by Infocatcher** 2017-01-18 19:54 UTC
Labels: compatibility

**Comment by Dimas-sc** [comment] 2017-01-18 19:56
Thx!! Waiting for it :D

**Comment by Rikk** [comment] 2017-01-19 10:34
The toggle works intermittently in new FF 51, ie. after some tries (ctrl+alt+t) it become enabled and after some tries it is disabled.

**Comment by Infocatcher** [comment] 2017-01-19 21:03
Also corrected: http://forums.mozillazine.org/viewtopic.php?p=14728853#p14728853
`x` Correctly update window title and style, if toggled private state of selected non-remote tab (restored non-remote private tab) in Firefox 51+ (<a href="https://github.com/Infocatcher/Private_Tab/issues/237">#237</a>, <a href="https://github.com/Infocatcher/Private_Tab/issues/239">#239</a>).

For now I don't like to touch AMO to not break review queue...

Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.2.1.1pre-fx-sm.xpi">private_tab-0.2.1.1pre-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/2afc18c719e70ebce60083efc6ad78c0250e9262">source code</a>)

And now non-AMO versions will update automatically to pre-releases (since now it's not clear, how to use them on non-test browser versions).

**Comment by Infocatcher** [comment] 2017-01-19 21:09
> The toggle works intermittently in new FF 51, ie. after some tries (ctrl+alt+t) it become enabled and after some tries it is disabled.

Only hotkey or "Private Tab" checkbox from tab context menu too? And what exactly happens: nothing instead of toggling or something else?

**Comment by Rikk** [comment] 2017-01-20 23:34
Both. It is like the tab get cloned and old tab is closed, but the new cloned tab more often doesn't become private.
In following video, each reload of the tab means ctrl+alt+t hotkey was pressed, note that sometimes it even fails to load the page and opens a blank page:
[ScreenCapture_20-01-2017 1.wmv.gz](https://github.com/Infocatcher/Private_Tab/files/720730/ScreenCapture_20-01-2017.1.wmv.gz)

In this other recording, it is interesting to note that when I toggle private state of the tab before I open it first, it seems to work much better:
[ScreenCapture_20-01-2017 2.wmv.gz](https://github.com/Infocatcher/Private_Tab/files/720731/ScreenCapture_20-01-2017.2.wmv.gz)

(Sorry about the Gzip, I tried to upload as Zip, but GitHub didn't accept, but this shouldn't be a problem I hope)

**Comment by Rikk** [comment] 2017-01-21 01:26
This problem also affects [Multiple Tab Handler](https://github.com/piroor/multipletab), I can't properly move a selection, for example, with one normal tab and one private tab to a new window -- the normal tab is moved and the other becomes a weird blank "New Tab" with site's favicon but broken and impossible to close. It once made the browser into a loop and freeze using high-cpu.

Mozilla and their broken releases! Very, very unhappy devs. Can't they give users more than two releases without breaking things and bad changes!?

**Comment by Infocatcher** [comment] 2017-01-21 11:57
> note that sometimes it even fails to load the page and opens a blank page

Will be better with 95a44ce019dc8727688333a4ea1dff98b479ca50

Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.2.1.1pre2-fx-sm.xpi">private_tab-0.2.1.1pre2-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/741b1856cb0f0b781037d9e32b52183283079f04">source code</a>).
<br>

> For example, I can't properly move a selection of one normal tab and one private tab to a new window -- the normal tab is moved and the other becomes a weird blank "New Tab" with site's favicon but broken and impossible to close. It once made the browser into a loop and freeze using high-cpu.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1279094
And even still "unconfirmed"...

**Comment by Rikk** [comment] 2017-01-21 13:52
Blank page fix seems not effective yet :worried:
If you toggle very fast (tip: keep hotkey pressed), still happens 100% of the time.

About moving tabs, I don't have e10s thing enabled, and it was working properly in 50.1 until I updated to 51, then I'm not sure it is the same case of this bugzilla...
('Unconfirmed for years' is the result of bug reports made by unimportant persons like me and this guy... I never had luck reporting bugs for them)

**Comment by Infocatcher** [comment] 2017-01-23 18:39
> Blank page fix seems not effective yet 😟
> If you toggle very fast (tip: keep hotkey pressed), still happens 100% of the time.

Will be better with following corrections: a5ef6b2061a4bea1f0e4a289b2eb5838978acbbc, 549de7b3ce2393695beedda50fd62481d89073dc
Now command to toggle private state will do nothing, if previous duplication is still in progress and will wait up to 300 ms, if looks like tab isn't initialized yet.

Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.2.1.2pre2-fx-sm.xpi">private_tab-0.2.1.2pre2-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/835fc4cb12ac1e61b8755347c08fc8ed00c7974a">source code</a>)
