### ISSUE TITLE
Open Link in New Private Tab Broken [Ffx 41] [OSX] [E10s]

### ISSUE THREAD

**Issue by theHokage** [Infocatcher/Private_Tab#181] opened 2015-06-18 15:46 UTC
Right Click > Open in New Private Tab is broken in Nightly. Possible e10s issue. Currently request simply fails.

**Comment by Infocatcher** [comment] 2015-06-18 15:54
Yes, many things are broken with enabled e10s: #162
This caused by the same reason as #182: content process doesn't initialized yet at tab opening state.

**Comment by theHokage** [comment] 2015-06-23 14:09
Interesting. I assumed this issue - #181, was due to e10s, but since the new private tab shortcut works in windows, I figured #182 had a good chance of not being due to e10s. My bad!

**Comment by Infocatcher** [comment] 2016-08-25 18:33
Most of e10s-related bugs (include this one) should be fixed in latest version:
https://addons.mozilla.org/addon/private-tab/versions/0.2.0

**Closed by Infocatcher** 2016-08-25 18:33 UTC
Labels: bug, compatibility
